### PR TITLE
Cleanup usage of getArbetsUnderlag.

### PR DESCRIPTION
**Pull request by kaj**
Don't check the ettStudieresultat for matching results twice for each result to report.  Rather than calling harArbetsUnderlag and if that returns true start over by calling getArbetsUnderlag, just call getArbetsUnderlag and check if there was a result or not.

Also, get rid of two unneeded temporary variables.

(Tested successfully on my localhost with the test course.)

### CODE REVIEW

**Comment by bjfr** [comment]
Har ni nån kodstandard? Ser att variabler ibland startar med stor bokstav, ibland med liten. Brukar ju vara standard att namnge konstanter UPPERCASE_MED_UNDERSCORE, och icke konstanter lowerCamelCase...

**Comment by kaj** [comment]
I think we use lowerCamelCase for variables (which, in this strange language is defined with the keyword `const`), and UpperCamelCase where Ladok forces us to. UPPERCASE_MED_UNDERSCORE should be reserved for actual constansts, that has the same value every time we run the program.

**Comment by me97esn** [comment]
Won't have time to look at this PR until earliest tuesday, or more probable on wednesday since we have demo and planning on tuesday.

**Comment by bjfr** [comment]
Except for the fact that some variables are defined with uppercase (such as Betygsgrad and Uid) everything looks fine. And these variables have not been changed by this PR... Should I merge it?

**Pull request merged**
